### ISSUE TITLE
compile issues in windows

### ISSUE THREAD

**Issue by afterburn420** [mvasilchuk/yasem#10]
I am using using QT Creator for windows with mingw compiler (G++).
QT version 5.4 and recent source code.
I have tried several versions of ffmpeg.
I can not get the libraries to link to the code - or the compiler to find it.
I get the error when running qmake or compiling--
error: avutil is required, but compiler can not find it

What am I doing wrong - wrong IDE, compiler, location of libs, or syntax when linking.
Any help figuring out why I am getting this error would be appreciated.

**Comment by mvasilchuk** [comment]
Try to add ffmpeg (or libav) headers and libs to LIBRARY_PATH (libs) and CPLUS_INCLUDE_PATH (headers). I think you should download libs from http://builds.libav.org/windows/release-gpl/

**Comment by mvasilchuk** [comment]
If you're using QtCreator you may open  Projects tab and then add that env variables into "Build"->"Build environment". Add LIBRARY_PATH=<path to libs> and CPLUS_INCLUDE_PATH=<path to include dir>

**Comment by afterburn420** [comment]
Thank you - I was trying to link within the yasem.pro file...and it wasn't working.
No avutil error now - I was dreading having to redo the project for VS2010 ultimate.
