### ISSUE TITLE
Git Not pulling QTAV folder

### ISSUE THREAD

**Issue by gh0st19** [mvasilchuk/yasem#14]
I keep getting permission errors when trying to clone in git. Everything seems to work fine but it won't pull the QTAV folder.

**Comment by mvasilchuk** [comment]
Fixed. I've accidentally changed QtAV URL.
If doesn't help open plugins/yasem-qtav-mediaplayer/.gitmodules and check that URL starts with https://github.com/mvasilchuk (but not with git@github.com:mvasilchuk)
