### ISSUE TITLE
yasem-web-browser

### ISSUE THREAD

**Issue by Ninissh** [mvasilchuk/yasem#15]
Ubuntu 14.04 LTS
When i try to compile i get this error,
webview.cpp:285:52: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
         origin.addAccessWhitelistEntry("http", "", QWebSecurityOrigin::AllowSubdomains);
                                                    ^
webview.cpp:286:16: error: ‘class QWebSecurityOrigin’ has no member named ‘addAccessWhitelistEntry’
         origin.addAccessWhitelistEntry("qrc", "", QWebSecurityOrigin::AllowSubdomains);
                ^
webview.cpp:286:51: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
         origin.addAccessWhitelistEntry("qrc", "", QWebSecurityOrigin::AllowSubdomains);
                                                   ^
webview.cpp:287:16: error: ‘class QWebSecurityOrigin’ has no member named ‘addAccessWhitelistEntry’
         origin.addAccessWhitelistEntry("http", "www.youtube.com", QWebSecurityOrigin::AllowSubdomains);
                ^
webview.cpp:287:67: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
         origin.addAccessWhitelistEntry("http", "www.youtube.com", QWebSecurityOrigin::AllowSubdomains);
                                                                   ^
make[2]: *** [release/webview.o] Erreur 1
make[2]: quittant le répertoire « /home/enhaut/yasem/plugins/yasem-web-browser »
make[1]: *** [release] Erreur 2
make[1]: quittant le répertoire « /home/enhaut/yasem/plugins/yasem-web-browser »
make: *** [sub-plugins-yasem-web-browser-make_first] Erreur 2
Am i missing some thing?

Fix problem

**Comment by Ninissh** [comment]
need that for my iptv provider.
Get 
STUB ][04:47:23:858] virtual void yasem::QtAvMediaPlayer::aspectRatio(ASPECT_RATIO):  9 
[WARN ][04:47:23:858] status ignored 
[http @ 0x7fad50006e60] HTTP error 404 Not Found
[WARN ][04:47:24:685] status ignored

**Comment by Ninissh** [comment]
Try qt 5.2 and 5.3,command line and qtcreator same result

**Comment by Ninissh** [comment]
Can get to portal but wont play channel,404

**Comment by Ninissh** [comment]
Whit qt 5.3 get this after compilation ok.
./yasem 
[STUB ][05:27:11:310] yasem::SamsungSmartTvWebPlugin::SamsungSmartTvWebPlugin()
[WARN ][05:27:11:317] Cyclic dependency in plugin "webkit-browser" with "desktop-gui"
[STUB ][05:27:11:317] void yasem::WebView::loadFixes()
[STUB ][05:27:11:317] QString yasem::WebView::loadFix(const QString&)
[STUB ][05:27:11:318] QString yasem::WebView::loadFix(const QString&)
[STUB ][05:27:11:338] bool yasem::WebPage::stb(yasem::StbPlugin*)
[STUB ][05:27:11:352] yasem::InterceptorManager::InterceptorManager(yasem::WebPage*)
[WARN ][05:27:11:353] Cyclic dependency in plugin "web-gui" with "desktop-gui"
[STUB ][05:27:11:353] virtual PLUGIN_ERROR_CODES yasem::QtAvMediaPlayer::initialize()
[STUB ][05:27:11:357] virtual PLUGIN_ERROR_CODES yasem::DesktopGUI::initialize()
[STUB ][05:27:11:399] virtual void yasem::QtAvMediaPlayer::aspectRatio(ASPECT_RATIO):  0
[STUB ][05:27:11:419] virtual void yasem::GuiConfigProfile::start()
[STUB ][05:27:11:420] bool yasem::WebPage::stb(yasem::StbPlugin*)
[STUB ][05:27:11:420] void yasem::WebPage::resetPage()
[STUB ][05:27:11:420] virtual bool yasem::WebPluginFactoryImpl::addPlugin(yasem::StbPlugin*)
[STUB ][05:27:11:420] virtual void yasem::WebPluginFactoryImpl::refreshPlugins()
[STUB ][05:27:11:420] void yasem::WebView::onLoadStarted()
SIGSEGV
0: ./yasem() [0x408f9a]
1: ./yasem() [0x408958]
2: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f4e0cd79340]
Abandon (core dumped)

**Comment by sunu** [comment]
@Ninissh Any pointers how to fix this?

**Comment by mvasilchuk** [comment]
Hi. You should either use a never version of Qt or, in case it can't be compiled even with a new version , open subproject `yasem-web-browser` and find a method `onUrlChanged`. In this method comment out everything between `#if QT_VERSION >= QT_VERSION_CHECK(5, 2, 0)` and `#endif`
