### ISSUE TITLE
 HTTP error 404 Not Found

### ISSUE THREAD

**Issue by Ninissh** [mvasilchuk/yasem#16]
Ubuntu 14.04 LTS QT5.3.2 Intel® Core™ i3-3220 CPU @ 3.30GHz × 4  Gallium 0.4 on AMD TAHITI 64 bit.
Compile fine,can lunch yassem,get into portal and can see channel list but i get this respond when i try to select one.Any hint would make my day.
Sorry but english is not my native language.

[DEBUG][00:13:46:346] "ffrt2 http://lb1.iptvserver.tv:1935/redirect/LiveEdge/********************?scheme=m3u8&token=40229d5de4c98fc6020c66b19ac5896f" ""
[DEBUG][00:13:46:346] matched proto: "ffrt2" , url: "http://lb1.iptvserver.tv:1935/redirect/LiveEdge/********************?scheme=m3u8&token=40229d5de4c98fc6020c66b19ac5896f"
[STUB ][00:13:46:346] virtual void yasem::QtAvMediaPlayer::aspectRatio(ASPECT_RATIO):  9
[DEBUG][00:13:46:346] Loading  QVariant(QString, "http://lb1.iptvserver.tv:1935/redirect/LiveEdge/********************D?scheme=m3u8&token=40229d5de4c98fc6020c66b19ac5896f")  ...
[DEBUG][00:13:46:346] "all closed and reseted"
[DEBUG][00:13:46:346] "avformat_open_input: d->format_ctx:'0x7fb398001d00', url:'http://lb1.iptvserver.tv:1935/redirect/LiveEdge/********************?scheme=m3u8&token=40229d5de4c98fc6020c66b19ac5896f'..."
[DEBUG][00:13:46:346] [MEDIA]: status changed: 2
[WARN ][00:13:46:346] status ignored                               <----------
[http @ 0x7fb398000f20] HTTP error 404 Not Found        <----------
[DEBUG][00:13:54:837] "avformat_open_input: url:'http://lb1.iptvserver.tv:1935/redirect/LiveEdge/********************?scheme=m3u8&token=40229d5de4c98fc6020c66b19ac5896f' ret:-5"
[WARN ][00:13:54:837] Can't open media:  "failed to open media"
[DEBUG][00:13:54:837] [MEDIA]: status changed: 8
[WARN ][00:13:54:837] status ignored
[WARN ][00:13:54:837] "Load failed!"

**Comment by mvasilchuk** [comment]
Hi. Are you sure you have all required codecs installed? Try to install codecs for restricted formats (https://help.ubuntu.com/community/RestrictedFormats). If doesn't help try to open the link in VLC or any other player to see its format.

**Comment by Ninissh** [comment]
Drop Ubuntu and went back to opensuse 13.1.
So will close this one.
Was a codecs problem.
Tough ubuntu would make it easy but was not the case.
Will let you know how it is going in opensuse.
