### ISSUE TITLE
'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'

### ISSUE THREAD

**Issue by afterburn420** [mvasilchuk/yasem#18]
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:34:92: warning: unused parameter 'context' [-Wunused-parameter]
 void QtAVMediaPlayerObject::customMessageHandler(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                                                                            ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:112:45: warning: unused parameter 'videoWidget' [-Wunused-parameter]
 void QtAVMediaPlayerObject::widget(QWidget *videoWidget)
                                             ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp: In member function 'virtual yasem::PluginObjectResult yasem::QtAVMediaPlayerObject::init()':
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:411:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(paused(bool)),                    &this->mediaSignalSender, SIGNAL(paused(bool)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:412:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(started()),                       &this->mediaSignalSender, SIGNAL(started()));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:413:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(stopped()),                       &this->mediaSignalSender, SIGNAL(stopped()));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:414:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(speedChanged(qreal)),             &this->mediaSignalSender, SIGNAL(speedChanged(qreal)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:415:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(repeatChanged(int)),              &this->mediaSignalSender, SIGNAL(repeatChanged(int)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:416:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(currentRepeatChanged(int)),       &this->mediaSignalSender, SIGNAL(currentRepeatChanged(int)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:417:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(startPositionChanged(qint64)),    &this->mediaSignalSender, SIGNAL(startPositionChanged(qint64)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:418:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(stopPositionChanged(qint64)),     &this->mediaSignalSender, SIGNAL(stopPositionChanged(qint64)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:419:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(positionChanged(qint64)),         &this->mediaSignalSender, SIGNAL(positionChanged(qint64)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:420:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(brightnessChanged(int)),          &this->mediaSignalSender, SIGNAL(brightnessChanged(int)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:421:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(contrastChanged(int)),            &this->mediaSignalSender, SIGNAL(contrastChanged(int)));
                                                                          ^
C:\yasem-03132015\yasem\plugins\yasem-qtav-mediaplayer\QtAvMediaPlayer\qtavmediaplayerobject.cpp:422:74: error: 'class yasem::QtAVMediaPlayerObject' has no member named 'mediaSignalSender'
     connect(mediaPlayer, SIGNAL(saturationChanged(int)),          &this->mediaSignalSender, SIGNAL(saturationChanged(int)));
                                                                          ^
Makefile.Release:1598: recipe for target 'release/qtavmediaplayerobject.o' failed
mingw32-make[3]: *** [release/qtavmediaplayerobject.o] Error 1
mingw32-make[3]: Leaving directory 'C:/yasem-03132015/build1/plugins/yasem-qtav-mediaplayer/QtAvMediaPlayer'
mingw32-make[2]: *** [release] Error 2
Makefile:34: recipe for target 'release' failed
mingw32-make[2]: Leaving directory 'C:/yasem-03132015/build1/plugins/yasem-qtav-mediaplayer/QtAvMediaPlayer'
mingw32-make[1]: *** [sub-QtAvMediaPlayer-make_first-ordered] Error 2
Makefile:83: recipe for target 'sub-QtAvMediaPlayer-make_first-ordered' failed
mingw32-make[1]: Leaving directory 'C:/yasem-03132015/build1/plugins/yasem-qtav-mediaplayer'
makefile:145: recipe for target 'sub-plugins-yasem-qtav-mediaplayer-make_first' failed
mingw32-make: *** [sub-plugins-yasem-qtav-mediaplayer-make_first] Error 2
01:15:15: The process "C:\Qt2\Qt5.4.0\Tools\mingw491_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project yasem (kit: Desktop Qt 5.4.0 MinGW 32bit)
When executing step "Make"
01:15:15: Elapsed time: 04:07.

**Comment by mvasilchuk** [comment]
Fixed.

**Comment by afterburn420** [comment]
Cool it now compiles.

I noticed some comments about some things not working in windows.

At the moment I am not getting any playback in windows.

**Comment by afterburn420** [comment]
I just figured that I would send you an update. I have gathered a good number of computers to test the software when it gets close to release.I will get the website when it gets closer to time also.
____________________________________________________________
4 Fish to Never Eat
Click to Learn 4 Fish to NEVER Eat &#40;avoid these like the plague!&#41;
http://thirdpartyoffers.juno.com/TGL3131/552f3b387e0ec3b38139bst03duc
