### ISSUE TITLE
error compiling yasem yasem::WebPage

### ISSUE THREAD

**Issue by ramoncarmenaty** [mvasilchuk/yasem#21]
when i try to compile yasem in ubuntu 14.04 i get this error

webpage.cpp: In constructor ‘yasem::WebPage::WebPage(yasem::WebView*)’:
webpage.cpp:52:30: error: ‘Accelerated2dCanvasEnabled’ is not a member of ‘QWebSettings’
     settings()->setAttribute(QWebSettings::Accelerated2dCanvasEnabled, true);

**Comment by mvasilchuk** [comment]
Try to comment out this line. It's not really necessary.
BTW, what Qt version do you use?

**Comment by ramoncarmenaty** [comment]
I'm using qt 5.2.1
