### ISSUE TITLE
Can't compile on Ubuntu 15.10

### ISSUE THREAD

**Issue by skerit** [mvasilchuk/yasem#28]
The compile fails on Ubuntu:

```
cd plugins/yasem-desktop-gui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/skerit/projecten/yasem/plugins/yasem-desktop-gui/yasem-desktop-gui.pro -o Makefile ) && make -f Makefile 
Project MESSAGE: Configuring module yasem-desktop-gui (v. 0.1.0, rev. f6269ea)
Project ERROR: Unknown module(s) in QT: qml quick quickwidgets
Makefile:141: recept voor doel 'sub-plugins-yasem-desktop-gui-make_first-ordered' is mislukt
make: *** [sub-plugins-yasem-desktop-gui-make_first-ordered] Fout 3
```

I have installed packages like libqt5quickwidgets5, but it still won't work

**Comment by mvasilchuk** [comment]
It could be some compiler cache issue. Try to remove folder like build-yasem-<your version> next to yasem's folder and rebuild the project.

**Comment by skerit** [comment]
I installed some more packages:

    sudo apt-get install qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5 libqt5webkit5-dev
    sudo apt-get build-dep qtmultimedia5-dev

After this compilation worked
