### ISSUE TITLE
yasem web-server fails with new git

### ISSUE THREAD

**Issue by Gfunk117** [mvasilchuk/yasem#29]
I am trying to build the newest yasem with the pvr functions but my build fails on web-server plugin.  I updated my Qt to 5.5 and pulled in the newest git a few times with the same errors.  Here is my log in qt creator:

/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: error: no matching function for call to 'yasem::HttpProxyThread::connect(QPointer<QTcpSocket>&, void (QAbstractSocket::*)(), yasem::HttpProxyThread::run()::__lambda6&)'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note: candidates are:
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:196:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const char *signal,
                                    ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:196:36: note:   candidate expects 5 arguments, 3 provided
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:199:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const QMetaMethod &signal,
                                    ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:199:36: note:   candidate expects 5 arguments, 3 provided
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:475:32: note: QMetaObject::Connection QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline QMetaObject::Connection QObject::connect(const QObject *asender, const char *asignal,
                                ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:475:32: note:   no known conversion for argument 2 from 'void (QAbstractSocket::*)()' to 'const char*'
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:213:43: note: template<class Func1, class Func2> static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType)
     static inline QMetaObject::Connection connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal,
                                           ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:213:43: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:245:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:245:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:254:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0) && (! QtPrivate::FunctionPointer<Func2>::IsPointerToMemberFunction)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:254:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:285:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:285:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:293:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:293:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:169:63: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_socket, &QTcpSocket::disconnected, on_disconnect);
                                                               ^
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: error: no matching function for call to 'yasem::HttpProxyThread::connect(QPointer<QTcpSocket>&, void (QAbstractSocket::*)(), yasem::HttpProxyThread::run()::__lambda6&)'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note: candidates are:
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:196:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const char *signal,
                                    ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:196:36: note:   candidate expects 5 arguments, 3 provided
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:199:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const QMetaMethod &signal,
                                    ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:199:36: note:   candidate expects 5 arguments, 3 provided
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:475:32: note: QMetaObject::Connection QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline QMetaObject::Connection QObject::connect(const QObject *asender, const char *asignal,
                                ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:475:32: note:   no known conversion for argument 2 from 'void (QAbstractSocket::*)()' to 'const char*'
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:213:43: note: template<class Func1, class Func2> static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType)
     static inline QMetaObject::Connection connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal,
                                           ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:213:43: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:245:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:245:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:254:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0) && (! QtPrivate::FunctionPointer<Func2>::IsPointerToMemberFunction)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:254:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:285:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:285:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
In file included from /opt/Qt5/5.5/gcc_64/include/QtCore/QObject:1:0,
                 from /home/matt/yasem-git/yasem-sdk/abstractpluginobject.h:4,
                 from /home/matt/yasem-git/yasem-sdk/abstracthttpproxy.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.h:4,
                 from /home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:1:
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:293:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/Qt5/5.5/gcc_64/include/QtCore/qobject.h:293:13: note:   template argument deduction/substitution failed:
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:170:69: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QTcpSocket>'
     connect(m_proxy_socket, &QTcpSocket::disconnected, on_disconnect);
                                                                     ^
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp: In member function 'virtual void yasem::HttpProxyTcpServer::incomingConnection(qintptr)':
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:270:22: warning: declaration of 'thread' shadows a member of 'this' [-Wshadow]
     HttpProxyThread* thread = new HttpProxyThread(handle, static_cast<HttpProxyServer*>(parent()));
                      ^
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp: In constructor 'yasem::HttpProxyTcpServer::HttpProxyTcpServer(QObject*)':
/home/matt/yasem-git/plugins/yasem-web-server/httpproxyserver.cpp:275:55: warning: declaration of 'parent' shadows a member of 'this' [-Wshadow]
 HttpProxyTcpServer::HttpProxyTcpServer(QObject *parent):
                                                       ^
make[2]: *** [debug/httpproxyserver.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-plugins-yasem-web-server-make_first-ordered] Error 2
17:44:26: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project yasem (kit: Desktop Qt 5.5.0 GCC 64bit)
When executing step "Make"
17:44:26: Elapsed time: 30:42.

**Comment by mvasilchuk** [comment]
Fixed.

But what's your compiler and Qt versions?

**Comment by Gfunk117** [comment]
kit: Desktop Qt 5.5.0 GCC 64bit
gcc -v:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

g++ -v:

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by mvasilchuk** [comment]
I think the bug happened because your GCC  (4.8) doesn't support some features that my GCC (5.2) supports.
