### ISSUE TITLE
How to run yasem on mac os x Yosemite

### ISSUE THREAD

**Issue by cron35231** [mvasilchuk/yasem#32]
HI,

I compile yasem with QTCreator 5.5, I can run yasem in debug mode from QTCreator (Sometimes the program stop working and show message: yasem quit unexpectedly.), When I try to run yasem.app in the bin folder, the program wont work and give me the following message log: 

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: libyasem-sdk.0.dylib
  Referenced from: /Users/USER/Desktop/*/yasem.app/Contents/MacOS/yasem
  Reason: image not found

I try to move qt framework and plugins folder to yasem.app but same message. 

In Yasem release mode on QTCreator I get the following error: 

ld: warning: option -s is obsolete and being ignored
ld: internal error: atom not found in symbolIndex(__ZN5QHashIN5yasem3SDK10PluginRoleEPNS1_20AbstractPluginObjectEE6insertERKS2_RKS4_) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../bin/yasem.app/Contents/MacOS/libyasem-sdk.0.1.0.dylib] Error 1
make[1]: *** [release] Error 2
make: *** [sub-yasem-sdk-make_first-ordered] Error 2
01:04:01: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project yasem (kit: Desktop Qt 5.5.0 clang 64bit)
When executing step "Make".

I removed -s in common.pri and release mode compile the yasem but the program wont work from bin folder. Same error as debug mode:  Library not loaded: libyasem-sdk.0.dylib

Any help will be appreciate. 
Thank you.

**Comment by mvasilchuk** [comment]
Try to either copy libyasem-sdk.0.dylib from Contents/Plugins to Contents/MacOS/ (it should be in the same folder where executive file is) or run qmake with CONFIG-=app_bundle.

**Comment by cron35231** [comment]
The libyasem-sdk.0.dylib is in folder Contents/MacOS/ 
I can run the program from terminal with the following command:
cd folder_of_yasem_bin/yasem.app/Contents/MacOs/
./yasem

With that command I can run the program but clicking Yasem.app wont work. Maybe some problem with the path address. Thank you for your response.

**Comment by cron35231** [comment]
I fix the problem with install_name_tool. Something like this:
install_name_tool -id @executable_path/../MacOS/libyasem-sdk.0.dylib yasem.app/Contents/MacOS/libyasem-sdk.0.dylib
install_name_tool -change libyasem-sdk.0.dylib @executable_path/../MacOS/libyasem-sdk.0.dylib yasem.app/Contents/MacOS/yasem

Thank you.
