### ISSUE TITLE
compile on QT5.7 and 5.6.2

### ISSUE THREAD

**Issue by hmahn** [mvasilchuk/yasem#36]
This is compile log.

       Project MESSAGE: Configuring module yasem-web-browser (v. 0.1.0, rev. d76524c)
       Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

Could you port yasem to QT5.7?
(http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html)

**Comment by mvasilchuk** [comment]
QtWebKit is not available in the latest versions of Qt. It was replaced by QtWebView, but QtWebView doesn't provide necessary API methods to make the emulator work. 
Yasem mostly depends on QtWebKit's method addToJavaScriptWindowObject(), which can add C++ objects into browser and makes it possible to call native methods from JavaScript synchronously. However neither this method nor any other way to make synchronous call of native methods were not  implemented in QtWebView. 
So for now developing of Yasem is suspended until some fix for synchronous native code execution is available.
