### ISSUE TITLE
Build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by kormang** [mvasilchuk/yasem#43]
I have installed all packages listed in README.md and also qt5-default.
But when I run make I get this error:

`make[1]: Leaving directory '/home/user/yasem/yasem-core'
cd plugins/yasem-desktop-gui/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/user/yasem/plugins/yasem-desktop-gui/yasem-desktop-gui.pro ) && make -f Makefile 
Project MESSAGE: Configuring module yasem-desktop-gui (v. 0.1.0, rev. e7ba522)
Project ERROR: Unknown module(s) in QT: qml quick quickwidgets
Makefile:143: recipe for target 'sub-plugins-yasem-desktop-gui-make_first-ordered' failed
make: *** [sub-plugins-yasem-desktop-gui-make_first-ordered] Error 3
`
What else shoud be installed?

Thank you.

**Comment by Saentist** [comment]
Installation of this packages is needed
qtdeclarative5-dev
libqt5webkit5-dev
qtmultimedia5-dev
