### ISSUE TITLE
Dependency "Media player plugin" for "desktop-gui" not found! win7

### ISSUE THREAD

**Issue by mchakroun** [mvasilchuk/yasem#5]
Hi, I'm trying to compile yasem for windows, it builds and run but no desktop gui
Here is the Debug:

Starting D:\build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release\bin\yasem.exe...
[DEBUG] Library paths:  ("D:/Qt/5.3/mingw482_32/plugins", "D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin", "D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/libs", "D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/libs/plugins")
[DEBUG] Settings directory "C:/Users/Mohamed Chakroun/AppData/Roaming/yasem"
[DEBUG] Starting application...
[DEBUG] Looking for plugins...
[DEBUG] pluginsToLoad: ("desktop-gui", "dunehd-plugin", "ini-ds", "mag-api", "samsung-smart-tv-plugin", "tray-icon", "webkit-browser", "webserver-browser")
[DEBUG] PluginManager::listPlugins()
[DEBUG] Blacklisted plugins: ("vlc-mediaplayer", "qt-mediaplayer")
[DEBUG] Searching for plugins in "D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins"
[DEBUG] Found file: "libyasem-desktop-gui0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-desktop-gui0.a'"
[DEBUG] Found file: "libyasem-dunehd-api0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-dunehd-api0.a'"
[DEBUG] Found file: "libyasem-ini-datasource0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-ini-datasource0.a'"
[DEBUG] Found file: "libyasem-mag-api0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-mag-api0.a'"
[DEBUG] Found file: "libyasem-qtav-mediaplayer1.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-qtav-mediaplayer1.a'"
[DEBUG] Found file: "libyasem-samsung-smarttv-api0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-samsung-smarttv-api0.a'"
[DEBUG] Found file: "libyasem-tray-icon0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-tray-icon0.a'"
[DEBUG] Found file: "libyasem-web-browser0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-web-browser0.a'"
[DEBUG] Found file: "libyasem-web-server0.a"
[WARN ] "Plugin verification data mismatch in 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/libyasem-web-server0.a'"
[DEBUG] Found file: "yasem-desktop-gui0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "Desktop GUI plugin"
[DEBUG] Registered "config" as profile class ID
[DEBUG] Found STB plugin: "Desktop GUI plugin"
[DEBUG] Found STB submodels: ""
[DEBUG] Found file: "yasem-dunehd-api0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "DuneHD JS API implementation"
[DEBUG] Registered "dunehd" as profile class ID
[DEBUG] Found STB plugin: "DuneHD JS API implementation"
[DEBUG] Found STB submodels: ""
[DEBUG] Found file: "yasem-ini-datasource0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "INI datasource provider"
[DEBUG] Found file: "yasem-mag-api0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "MAG API implementation"
[DEBUG] Registered "mag" as profile class ID
[DEBUG] Found STB plugin: "MAG API implementation"
[DEBUG] Found STB submodels: "MAG100, MAG200, MAG245, MAG250, MAG254, MAG255, MAG260, MAG270, MAG275, AuraHD"
[DEBUG] Found file: "yasem-qtav-mediaplayer1.dll"
[WARN ] "The plugin 'D:/build-yasem-Desktop_Qt_5_3_MinGW_32bit-Release/bin/plugins/yasem-qtav-mediaplayer1.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)"
[DEBUG] Found file: "yasem-samsung-smarttv-api0.dll"
[STUB ] yasem::SamsungSmartTvWebPlugin::SamsungSmartTvWebPlugin()
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "samsung Smart TV API implementation"
[DEBUG] Registered "samsung" as profile class ID
[DEBUG] Found STB plugin: "samsung Smart TV API implementation"
[DEBUG] Found STB submodels: ""
[DEBUG] Found file: "yasem-tray-icon0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "Tray icon plugin"
[DEBUG] Found file: "yasem-web-browser0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "Webkit browser plugin"
[DEBUG] Found file: "yasem-web-server0.dll"
[DEBUG] Registering plugin roles...
[DEBUG] Registering plugin dependencies...
[DEBUG] Plugin loaded: "Web server plugin"
[DEBUG] initPlugins()
[DEBUG]  Plugin "desktop-gui" initialization...
[DEBUG]  Loading dependencies for "desktop-gui" ...
[DEBUG]  Trying to load dependency "Browser plugin"  for "Desktop GUI plugin"
[DEBUG] -- Plugin "webkit-browser" initialization...
[DEBUG] -- Loading dependencies for "webkit-browser" ...
[DEBUG] -- Trying to load dependency "GUI plugin"  for "Webkit browser plugin"
[WARN ] Cyclic dependency in plugin "webkit-browser" with "desktop-gui"
[DEBUG] -- Dependencies for "webkit-browser" have been loaded.
[STUB ] void yasem::WebView::loadFixes()
[STUB ] QString yasem::WebView::loadFix(const QString&)
[STUB ] QString yasem::WebView::loadFix(const QString&)
[STUB ] bool yasem::WebPage::stb(yasem::StbPlugin_)
[STUB ] yasem::InterceptorManager::InterceptorManager(yasem::WebPage_)
[DEBUG] wtf child: (yasem::WebView(0x12aa9d00, name = "WebView") ) 
[DEBUG] -- Plugin "webkit-browser" initialized
[DEBUG]  Dependency "Browser plugin" initialized
[DEBUG]  Trying to load dependency "Datasource plugin"  for "Desktop GUI plugin"
[DEBUG] -- Plugin "ini-ds" initialization...
[DEBUG] -- Loading dependencies for "ini-ds" ...
[DEBUG] No dependencies for "ini-ds" have been found
[DEBUG] -- Plugin "ini-ds" initialized
[DEBUG]  Dependency "Datasource plugin" initialized
[DEBUG]  Trying to load dependency "Media player plugin"  for "Desktop GUI plugin"
[WARN ] Dependency "Media player plugin" for "desktop-gui" not found!
[WARN ] Plugin "desktop-gui" won't be loaded because of missing dependencies!
[DEBUG]  Plugin "dunehd-plugin" initialization...
[DEBUG]  Loading dependencies for "dunehd-plugin" ...
[DEBUG]  Trying to load dependency "Browser plugin"  for "DuneHD JS API implementation"
[DEBUG]  Dependency "Browser plugin" initialized
[DEBUG]  Dependencies for "dunehd-plugin" have been loaded.
[DEBUG]  Plugin "dunehd-plugin" initialized
[DEBUG]  Plugin "mag-api" initialization...
[DEBUG]  Loading dependencies for "mag-api" ...
[DEBUG]  Trying to load dependency "Datasource plugin"  for "MAG API implementation"
[DEBUG]  Dependency "Datasource plugin" initialized
[DEBUG]  Trying to load dependency "Browser plugin"  for "MAG API implementation"
[DEBUG]  Dependency "Browser plugin" initialized
[DEBUG]  Trying to load dependency "Media player plugin"  for "MAG API implementation"
[WARN ] Dependency "Media player plugin" for "mag-api" not found!
[WARN ] Plugin "mag-api" won't be loaded because of missing dependencies!
[DEBUG]  Plugin "samsung-smart-tv-plugin" initialization...
[DEBUG]  Loading dependencies for "samsung-smart-tv-plugin" ...
[DEBUG]  Trying to load dependency "Browser plugin"  for "samsung Smart TV API implementation"
[DEBUG]  Dependency "Browser plugin" initialized
[DEBUG]  Trying to load dependency "Datasource plugin"  for "samsung Smart TV API implementation"
[DEBUG]  Dependency "Datasource plugin" initialized
[DEBUG]  Trying to load dependency "Media player plugin"  for "samsung Smart TV API implementation"
[WARN ] Dependency "Media player plugin" for "samsung-smart-tv-plugin" not found!
[WARN ] Plugin "samsung-smart-tv-plugin" won't be loaded because of missing dependencies!
[DEBUG]  Plugin "tray-icon" initialization...
[DEBUG]  Loading dependencies for "tray-icon" ...
[DEBUG] No dependencies for "tray-icon" have been found
[DEBUG]  Plugin "tray-icon" initialized
[DEBUG]  Plugin "webserver-browser" initialization...
[DEBUG]  Loading dependencies for "webserver-browser" ...
[DEBUG]  Trying to load dependency "Browser plugin"  for "Web server plugin"
[DEBUG]  Dependency "Browser plugin" initialized
[DEBUG]  Dependencies for "webserver-browser" have been loaded.
[DEBUG] Listening to port  9999 ...
[DEBUG]  Plugin "webserver-browser" initialized
[DEBUG] Initialization finished

**Comment by afterburn420** [comment]
Is there any way to get a pre-compiled windows executable to try?

Due to a lightning strike my Linux machine was destroyed.

I am working on building another to compile with - but it may take me a while to finish.

**Comment by mvasilchuk** [comment]
I can try to compile it. I'll send you a binary today later.

2015-01-02 4:27 GMT+02:00 afterburn420 <notifications@github.com>:

> Is there any way to get a pre-compiled windows executable to try?
>
> Due to a lightning strike my Linux machine was destroyed.
>
> I am working on building another to compile with - but it may take me a
> while to finish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mvasilchuk/yasem/issues/5#issuecomment-68506036>.
>



-- 
Best regards,
Maxim Vasilchuk

**Comment by afterburn420** [comment]
Thank you - you are the man

**Comment by mvasilchuk** [comment]
Hi. Sorry, couldn't build it yesterday. I forgot my Windows on Virtualbox
was reinstalled and I haven't configured it yet.

2015-01-03 8:28 GMT+02:00 afterburn420 <notifications@github.com>:

> Thank you - you are the man
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mvasilchuk/yasem/issues/5#issuecomment-68585326>.
>



-- 
Best regards,
Maxim Vasilchuk
