### ISSUE TITLE
Blank Video issue

### ISSUE THREAD

**Issue by CharafHormi** [mvasilchuk/yasem#7]
Hello there,
I have come across an issue on Yasem ,  the video on fullscreen doesn’t show up, just white/blank and audio working.
It does show up when I'm on the channels list though.
http://gyazo.com/40e7cd017cdbee095c6e2ed45c727a1d
http://gyazo.com/0643c27bd54a9f388185824fafdc696e
I'm tried on both Ubuntu and Mint VMs same issue on 3 different portals(Stalker based).

**Comment by afterburn420** [comment]
That seems to be the problem that I am having.

would [ player()->raise() if state==1 ] be the exact code  -  and where to find the gstb::setPIG function

**Comment by afterburn420** [comment]
in the code of gstb.cpp 

bool GStb::GetPIG()
{
    STUB();
    return false;
}

what would the code be for this fix?


bool GStb::GetPIG()
{
    STUB();If state==1; player()->raise();
    return false;
}

Is this correct or is my syntax wrong

**Comment by ashikhman** [comment]
afterburn420:
Add player()->raise(); after player()->fullscreen(true); inside if(state == 1) statement.

void GStb::SetPIG(int state, float scale, int x, int y)
{
    STUB() << state << scale << x << y;

    if(state == 1)
    {
        player()->fullscreen(true);
        player()->raise();
    }
    else
    {
        player()->fullscreen(true);
        if(x >= 0 && y >= 0)
            player()->move(x, y);
    }

    player()->resize();
}

**Comment by mvasilchuk** [comment]
Hi. I've tested this patch and it looks like it makes some portals work incorrect. But anyways I fixed this issue by adding browser transparency (it's limited now but works). Try to update to the latest version but remove that patch first if you've applied it.

**Comment by afterburn420** [comment]
The new patch is working great - I have it compiled on arch Linux VM and it's sweet.

If anyone out there has a compiled windows version then I would really appreciate a copy.

I look forward to seeing what the future of this project brings.

Thank you Maxim for this software, it is a close rival to my mag254 box.

P.S. Maxim, I have this cloned to yasem-test if you would like to use it to try new things without the worry of breaking the current code (for alpha or beta test for the public)

**Comment by mvasilchuk** [comment]
You may also make a pull request if you have any changes.

**Comment by afterburn420** [comment]
I will see about that when I get the time - thanks

**Comment by afterburn420** [comment]
OK I have a fork of yasem to afterburn420/yasem and a clone to afterburn420/yasem-test now
